working state v1

diff --git a/cli/.kic/commands/build/imdb b/cli/.kic/commands/build/imdb
--- a/cli/.kic/commands/build/imdb
+++ b/cli/.kic/commands/build/imdb
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-#name: imdb
-#short: Build and deploy the IMDb reference app to the local cluster
+#name: imdb-with-scaling
+#short: Build and deploy the IMDb app with ML scaling agent to the local cluster
 
 cd "$REPO_BASE" || exit
 
@@ -11,25 +11,35 @@ if [ ! -d deploy ]; then echo "$REPO_BASE/deploy directory not found. Please cd 
 if [ ! -d deploy/apps ]; then echo "$REPO_BASE/deploy/apps directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d deploy/apps/imdb ]; then echo "$REPO_BASE/deploy/apps/imdb directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d deploy/apps/webv ]; then echo "$REPO_BASE/deploy/apps/webv directory not found. Please cd to an appropriate directory"; exit 1; fi
+if [ ! -d deploy/apps/ml-scaling-agent ]; then echo "$REPO_BASE/deploy/apps/ml-scaling-agent directory not found. Please cd to an appropriate directory"; exit 1; fi
 
-# delete webv and imdb
+# delete existing deployments
 kubectl delete -f deploy/apps/webv --ignore-not-found=true --wait=false
 kubectl delete -f deploy/apps/imdb --ignore-not-found=true --wait=false
+kubectl delete -f deploy/apps/ml-scaling-agent --ignore-not-found=true --wait=false
 
-# build and push the local image
+# build and push the images
 docker build /workspaces/imdb-app -t k3d-registry.localhost:5500/imdb-app:local
 docker push k3d-registry.localhost:5500/imdb-app:local
+
+docker build -t k3d-registry.localhost:5500/ml-scaling-agent:latest -f ML/Dockerfile ML/
+docker push k3d-registry.localhost:5500/ml-scaling-agent:latest
 
 # wait for delete to finish
 kubectl wait pod -l app=webv -n imdb --for delete --timeout=30s
 kubectl wait pod -l app=imdb -n imdb --for delete --timeout=30s
+kubectl wait pod -l app=ml-scaling-agent -n imdb --for delete --timeout=30s
 
-# deploy local app and re-deploy webv
+# deploy applications
 kubectl apply -f deploy/apps/imdb
 kubectl wait pod -l app=imdb -n imdb --for condition=ready --timeout=30s
+
+kubectl apply -f deploy/apps/ml-scaling-agent
+kubectl wait pod -l app=ml-scaling-agent -n imdb --for condition=ready --timeout=30s
+
 kubectl apply -f deploy/apps/webv
 kubectl wait pod -l app=webv -n imdb --for condition=ready --timeout=30s
 
-# show status and curl results
+# show status
 kubectl get pods -n imdb
-http localhost:30080/version
+http localhost:30080/version 
